server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 875515445Bob
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 10
      #获取连接时，检测语句:
      connection-test-query: select 1
      connection-timeout: 20000
      #其它属性
      data-source-properties:
        cachePrepStmts: true
        dataSource.cachePrepStmtst: true
        dataSource.prepStmtCacheSize: 250
        dataSource.prepStmtCacheSqlLimit: 2048
        dataSource.useServerPrepStmts: true
  data:
    redis:
      host: 192.168.254.128
      port: 6379
      password: 123456
      database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据过期时间

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键生成策略
      id-type: ASSIGN_ID


reggie:
  path: D:\reggie-master\imgs\